DROP TABLE IF EXISTS instructions CASCADE;
CREATE TABLE instructions (
  id SERIAL PRIMARY KEY NOT NULL,
  keyword VARCHAR(255) NOT NULL,
  instructions text NOT NULL,
  bookmarked BOOLEAN NOT NULL DEFAULT FALSE
);