INSERT INTO aid(tag, patterns, responses, context_set, bookmarked)
VALUES
("Cuts", ["What to do if Cuts?", "How to cure Cuts?", "Which medicine to apply for Cuts?", "what to apply on cuts?", "Cuts"], ["Wash the cut properly to prevent infection and stop the bleeding by applying pressure for 1-2 minutes until bleeding stops. Apply Petroleum Jelly to make sure that the wound is moist for quick healing. Finally, cover the cut with a sterile bandage. Pain relievers such as acetaminophen can be applied."], NULL, false),
("Abrasions", ["how do you treat abrasions?", "Do Abrasions cause scars?", "Abrasions", "what to do if abrasions?", "Which medicine to apply for abrasions?", "How to cure abrasions?"], ["Begin with washed hands. Gently clean the area with cool to lukewarm water and mild soap. Remove dirt or other particles from the wound using sterilized tweezers. For a mild scrape that’s not bleeding, leave the wound uncovered. If the wound is bleeding, use a clean cloth or bandage and apply gentle pressure to the area to stop any bleeding. Cover a wound that bled with a thin layer of topical antibiotic ointment, like Bacitracin, or a sterile moisture barrier ointment, like Aquaphor. Cover it with a clean bandage or gauze. Gently clean the wound and change the ointment and bandage once per day. Watch the area for signs of infection, like pain or redness and swelling. See your doctor if you suspect infection."], NULL, false),
("Stings", ["How do you treat Sting?", "Stings", "What to do if you get a sting?", "Which medicine to apply if sting?"], ["Remove any stingers immediately. Some experts recommend scraping out the stinger with a credit card. Applying ice to the site may provide some mild relief. Apply ice for 20 minutes once every hour as needed. Wrap the ice in a towel or keep a cloth between the ice and skin to keep from freezing the skin. Taking an antihistamine such as diphenhydramine (Benadryl) or a nonsedating one such as loratadine (Claritin) will help with itching and swelling. Take acetaminophen (Tylenol) or ibuprofen (Motrin) for pain relief as needed. Wash the sting site with soap and water. Placing hydrocortisone cream on the sting can help relieve redness, itching, and swelling."], NULL, false),
("Splinter", ["How to remove Splinters", "How to cure Splinters?", "What to do if I have splinters?", "How do you bring a splinter to the surface?"], ["1. SOAK IT IN EPSOM SALTS. Dissolve a cup of the salts into a warm bath and soak whatever part of the body has the splinter. Failing that, you can also put some of the salts onto a bandage pad and leave it covered for a day; this will eventually help bring the splinter to the surface. 2. VINEGAR OR OIL. Another simple way to draw out that stubborn splinter is to soak the affected area in oil (olive or corn) or white vinegar. Just pour some in a bowl and soak the area for around 20 to 30 minutes."], NULL, false),
("Sprains", ["How do you treat a sprain?", "what to do if i get a sprain?", "Sprains", "How to cure sprains?"], ["Avoid using the injured area and try to keep weight off it. Use an ice pack to help reduce swelling, inflammation, and pain. Apply the ice for 10 to 20 minutes every hour or so, for the first few days. Compress the area with an elastic bandage to help reduce swelling. Elevate the injured area on a pillow or cushion, whenever possible, to help reduce swelling."], NULL, false),
("Burns", ["How to treat burns?", "What to do if you get burned?", "Burns", "How to cure burns?", "Which medicine to apply for burns?"], ["Cool the burn. Hold the burned area under cool (not cold) running water or apply a cool, wet compress until the pain subsides. Remove rings or other tight items from the burned area. Don't break blisters. If the burn is minor, clean the wound with mild soap and water. Apply an antibiotic ointment and a sterile bandage. Take an over-the-counter pain reliever if necessary. For more severe burns, seek medical attention."], NULL, false),
("Sprains", ["How do you treat a sprain?", "What to do if I get a sprain?", "Sprains", "How to cure sprains?"], ["Avoid using the injured area and try to keep weight off it. Use an ice pack to help reduce swelling, inflammation, and pain. Apply the ice for 10 to 20 minutes every hour or so, for the first few days. Compress the area with an elastic bandage to help reduce swelling. Elevate the injured area on a pillow or cushion, whenever possible, to help reduce swelling."], NULL, false),
("Fever", ["What to do if you have a fever?", "How to treat a fever?", "Fever", "How to cure a fever?", "Which medicine to take for fever?"], ["Rest and stay hydrated. Drink plenty of fluids to stay hydrated and rest as much as possible. Take over-the-counter fever reducers such as acetaminophen (Tylenol) or ibuprofen (Advil, Motrin) according to the recommended dosage. Keep the room temperature cool and dress in light clothing. If the fever persists or is accompanied by severe symptoms, seek medical attention."], NULL, false),
("Headache", ["What to do if you have a headache?", "How to treat a headache?", "Headache", "How to cure a headache?", "Which medicine to take for a headache?"], ["Find a quiet and dark room to rest. Apply a cold or warm compress to the painful area. Practice relaxation techniques such as deep breathing or meditation. Take over-the-counter pain relievers such as acetaminophen (Tylenol), ibuprofen (Advil, Motrin), or aspirin according to the recommended dosage. If headaches are persistent or severe, consult a healthcare professional."], NULL, false),
("Allergies", ["How to manage allergies?", "What to do if you have allergies?", "Allergies", "How to relieve allergy symptoms?", "Which medicine to take for allergies?"], ["Avoid allergens whenever possible. Use over-the-counter antihistamines such as loratadine (Claritin), cetirizine (Zyrtec), or fexofenadine (Allegra) to relieve symptoms. Use nasal sprays or rinses to alleviate congestion and rinse allergens from your nasal passages. Consult a healthcare professional for severe or persistent allergies."], NULL, false),
("Cough", ["How to relieve a cough?", "What to do if you have a cough?", "Cough", "How to cure a cough?", "Which medicine to take for a cough?"], ["Stay hydrated and drink plenty of fluids. Use cough drops or lozenges to soothe the throat. Try over-the-counter cough suppressants or expectorants to alleviate symptoms. Use a humidifier or take a steamy shower to help ease coughing. Seek medical attention if the cough persists or is accompanied by severe symptoms."], NULL, false),
("Stomachache", ["How to treat a stomachache?", "What to do if you have a stomachache?", "Stomachache", "How to cure a stomachache?"], ["Rest and avoid solid foods for a few hours. Sip clear liquids or drink ginger ale to help alleviate symptoms. Use over-the-counter antacids or acid reducers to relieve heartburn or indigestion. Apply a heating pad or hot water bottle to the abdomen for mild cramps. If the stomachache persists or worsens, consult a healthcare professional."], NULL, false),
("Rash", ["How to relieve a rash?", "What to do if you have a rash?", "Rash", "How to cure a rash?"], ["Keep the affected area clean and dry. Apply a mild, fragrance-free moisturizer to soothe the skin. Use over-the-counter hydrocortisone cream to reduce itching and inflammation. Take antihistamines to relieve allergic reactions. If the rash spreads, becomes severe, or is accompanied by other symptoms, seek medical attention."], NULL, false);
("CPR", ["How to perform CPR?", "CPR steps", "What is CPR?"], ["To perform CPR, follow these steps:\n1. Check the responsiveness of the person.\n2. Call emergency services.\n3. Begin chest compressions by pushing hard and fast in the center of the chest.\n4. Deliver rescue breaths using mouth-to-mouth or a CPR mask.\n5. Continue the cycle of compressions and breaths until help arrives."], NULL, false),
("Choking", ["What to do if someone is choking?", "Choking emergency", "Heimlich maneuver"], ["If someone is choking, follow these steps:\n1. Determine if the person can speak, cough, or breathe.\n2. Encourage the person to cough forcefully.\n3. Perform the Heimlich maneuver by standing behind them and applying upward pressure on the abdomen.\n4. If the person becomes unconscious, lower them to the ground and start CPR."], NULL, false),
("Nosebleed", ["What to do for a nosebleed?", "Stopping a nosebleed", "Nosebleed remedies"], ["To stop a nosebleed, follow these steps:\n1. Stay calm and sit upright, leaning slightly forward.\n2. Pinch the soft part of the nose, just above the nostrils, for about 10 minutes.\n3. Apply a cold compress or ice pack to the bridge of the nose.\n4. Avoid picking or blowing the nose forcefully after the bleeding has stopped.\n5. Seek medical attention if the bleeding persists for more than 20 minutes or if it's a result of an injury."], NULL, false),
("Seizures", ["What to do during a seizure?", "First aid for seizures", "Managing seizures"], ["During a seizure, follow these steps:\n1. Stay calm and keep others away from the person.\n2. Clear the area of any objects that could cause harm.\n3. Gently cushion the person's head and turn them onto their side.\n4. Do not restrain them or put anything in their mouth.\n5. After the seizure, offer reassurance and stay with the person until they recover."], NULL, false),
("Allergic Reactions", ["What to do for allergic reactions?", "First aid for allergies", "Managing allergic reactions"], ["For mild allergic reactions, follow these steps:\n1. Identify and remove the trigger if possible.\n2. Encourage the person to take their prescribed antihistamine medication.\n3. Apply a cold compress to reduce itching or swelling.\n4. If symptoms worsen or the person has a severe allergic reaction (anaphylaxis), call emergency services and administer an epinephrine auto-injector if available."], NULL, false),
("Heat Exhaustion", ["How to treat heat exhaustion?", "First aid for heat exhaustion", "Dealing with heat exhaustion"], ["To treat heat exhaustion, consider these steps:\n1. Move the person to a cool, shaded area.\n2. Help them lie down and elevate their legs slightly.\n3. Loosen or remove tight clothing and apply cool, wet cloths to their body.\n4. Encourage sips of water or a sports drink.\n5. If symptoms worsen or don't improve within 30 minutes, seek medical attention."], NULL, false),
("Fractures", ["What to do for a suspected fracture?", "First aid for fractures", "Dealing with fractures"], ["When suspecting a fracture, follow these steps:\n1. Help the person remain still and avoid unnecessary movement.\n2. Support the injured area with a makeshift splint using rolled-up newspapers, cardboard, or clothing.\n3. Apply ice packs wrapped in a cloth to reduce pain and swelling.\n4. Arrange for transportation to the nearest medical facility for further evaluation and treatment."], NULL, false),
("Eye Injuries", ["What to do for an eye injury?", "First aid for eye injuries", "Treating eye injuries"], ["For eye injuries, take these steps:\n1. Do not rub, touch, or apply pressure to the injured eye.\n2. Gently rinse the eye with clean water for at least 10 minutes if there are particles or chemicals in it.\n3. Cover the eye with a sterile dressing or clean cloth.\n4. Seek immediate medical attention, especially if there is severe pain, vision changes, or a foreign object embedded in the eye."], NULL, false);